# Generated by Django 4.1.1 on 2022-09-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialSourceType',
            new_name='Product',
        ),
    ]
