# Generated by Django 4.1.1 on 2022-09-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(blank=True, max_length=300, null=True)),
                ('orderBy', models.CharField(blank=True, max_length=300, null=True)),
                ('productList', models.CharField(blank=True, max_length=300, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('deliveryStatus', models.BooleanField()),
            ],
        ),
    ]
