# Generated by Django 4.1.1 on 2022-09-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryStatus',
            field=models.BooleanField(default=False),
        ),
    ]
