# Generated by Django 4.1.1 on 2022-09-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_order_deliverystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryStatus',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
